// @ts-ignore - generated by `prisma generate` (runs on install / vercel-build)
import { PrismaClient } from '@prisma/client';

/**
 * Shared Prisma client singleton.
 *
 * On serverless platforms (e.g. Vercel) every function invocation can reuse a
 * warm container, but new instances are also created frequently. Instantiating
 * a fresh PrismaClient per file/request quickly exhausts the database
 * connection pool (Supabase limits this aggressively). Caching a single client
 * on `globalThis` keeps connections bounded across invocations.
 */
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma: PrismaClient = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}
